BIN=pwm
OBJ=pwm.o

ARDCOREDIR=/usr/share/arduino/hardware/arduino/cores/arduino
CC=avr-gcc
OBJCOPY=avr-objcopy
CFLAGS= -I../incl/ -I$(ARDCOREDIR) -I$(ARDCOREDIR)/../../variants/standard -Wall -Os -DF_CPU=16000000UL -mmcu=atmega328p
PORT=/dev/ttyACM0

${BIN}.hex: ${BIN}.elf
	${OBJCOPY} -O ihex -R .eeprom $< $@

${BIN}.elf: ${OBJ}
	${CC} -o $@ $^

%.o: %.c
	${CC} ${CFLAGS} -c -o $@ $< 

install: ${BIN}.hex
	avrdude -F -V -c arduino -p ATMEGA328P -P ${PORT} -b 115200 -U flash:w:$<

clean:
	rm -f ${BIN}.elf ${BIN}.hex ${OBJ}.o
