ARDMK_DIR=/home/mtrempell/Projects/Arduino-Makefile

#BOARD_TAG = uno
#MCU = atmega328p
BOARD_TAG = mega2560
MCU = atmega2560
F_CPU = 16000000L
ARDUINO_LIBS += ros_lib

include $(ARDMK_DIR)/Arduino.mk
